"""empty message

Revision ID: ac35b7bdffa4
Revises: 3c15ecc927de
Create Date: 2022-03-29 20:05:09.600996

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac35b7bdffa4'
down_revision = '3c15ecc927de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('likes_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'likes_count')
    # ### end Alembic commands ###
